#!/bin/bash -ex

#configuration
haste_dir="/opt/haste-server"

# Set Hostname
HOSTNAME = haste
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# Check for root

LUID=$(id -u)
if [[ $LUID -ne 0 ]]; then
	echo "$0 must be run as root"
	exit 1
fi

# install function: invoke with "install" and then space-separated values

install ()
{
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

install git-core \
	build-essential \
	curl wget openssl \
	redis-server \
	libssl-dev \
	apache2 \
	webmin-apache \
	libapache2-mod-proxy-html \
	ssl-cert

# node dl with git
git clone http://github.com/ry/node.git /tmp/node
# node compile
cd /tmp/node && ./configure && make && make install
# npm install
cd /tmp && curl https://npmjs.org/install.sh | sh

# haste from git
git clone https://github.com/seejohnrun/haste-server.git $haste_dir
# config and install with npm
cd $haste_dir && npm install

a2enmod proxy_http
a2ensite haste
service apache2 reload



